import { SnakeGame } from '../games/arcade/SnakeGame.js';
import { BrickBreakerGame } from '../games/arcade/BrickBreakerGame.js';
import { SpaceShooterGame } from '../games/arcade/SpaceShooterGame.js';
import { PongGame } from '../games/arcade/PongGame.js';
import { FlappyDashGame } from '../games/reflex/FlappyDashGame.js';
import { TowerStackGame } from '../games/reflex/TowerStackGame.js';
import { Game2048 } from '../games/puzzle/Game2048.js';
import { TicTacToeGame } from '../games/puzzle/TicTacToeGame.js';
import { MemoryCardsGame } from '../games/puzzle/MemoryCardsGame.js';
import { DunkBasketballGame } from '../games/sports/DunkBasketballGame.js';
import { HighwayRacerGame } from '../games/racing/HighwayRacerGame.js';
import { CyberIcons } from '../components/CyberIcons.js';

export const CATEGORIES = [
  { id: 'all', name: 'All Games', icon: CyberIcons.all },
  { id: 'arcade', name: 'Arcade Classics', icon: CyberIcons.arcade },
  { id: 'reflex', name: 'Reflex & Action', icon: CyberIcons.reflex },
  { id: 'puzzle', name: 'Puzzle & Logic', icon: CyberIcons.puzzle },
  { id: 'sports', name: 'Sports & Physics', icon: CyberIcons.sports },
  { id: 'racing', name: 'Racing & Speed', icon: CyberIcons.racing }
];

export const GAMES_DATA = [
  // ==================== ARCADE CLASSICS (1-22) ====================
  {
    id: 'snake',
    title: 'Cyber Snake',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Guide the glowing cyber serpent, gobble digital energy orbs, avoid wall crashes and collect golden fruits.',
    difficulty: 'Medium',
    controls: ['arrows', 'wasd', 'swipe', 'touch_dpad'],
    instructions: 'Use Arrow Keys, WASD, Swipe, or On-Screen D-Pad to turn. Don’t hit the cyber perimeter or your own tail!',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Popular',
    factory: (session, canvas, input, audio) => new SnakeGame(session, canvas, input, audio)
  },
  {
    id: 'brick-breaker',
    title: 'Neon Brick Breaker',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Shatter vibrant prisms with high-velocity laser balls, powerup drops, and reactive paddle physics.',
    difficulty: 'Medium',
    controls: ['arrows', 'mouse', 'touch_drag'],
    instructions: 'Move paddle left and right to bounce the ball and demolish all bricks before running out of lives.',
    themeColor: '#EC4899',
    accentColor: '#00F2FE',
    badge: 'Classic',
    factory: (session, canvas, input, audio) => new BrickBreakerGame(session, canvas, input, audio)
  },
  {
    id: 'space-shooter',
    title: 'Galaxy Defender',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Pilot an interstellar starfighter through waves of alien drones, meteor swarms, and plasma bosses.',
    difficulty: 'Hard',
    controls: ['arrows', 'space', 'touch_action'],
    instructions: 'Navigate your ship and fire continuously to repel the alien armada.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Featured',
    factory: (session, canvas, input, audio) => new SpaceShooterGame(session, canvas, input, audio)
  },
  {
    id: 'asteroids',
    title: 'Cosmic Asteroids',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Vector-style space survival where you blast spinning asteroids into fragments with momentum thrust physics.',
    difficulty: 'Hard',
    controls: ['arrows', 'space', 'touch_action'],
    instructions: 'Rotate, apply thrusters, and shoot splitting space rocks.',
    themeColor: '#00F2FE',
    accentColor: '#FFD700',
    badge: 'Retro'
  },
  {
    id: 'pac-runner',
    title: 'Chomp Maze',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Navigate neon labyrinths, munch energy dots, and outmaneuver roaming cyber ghosts.',
    difficulty: 'Medium',
    controls: ['arrows', 'wasd', 'touch_dpad'],
    instructions: 'Navigate every turn, clear every dot, and grab power pellets to turn the tables.',
    themeColor: '#FFD700',
    accentColor: '#00F2FE',
    badge: 'Classic'
  },
  {
    id: 'pong',
    title: 'Cyber Pong 3000',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'The definitive two-paddle rally with hyper-speed spin curves, neon trails, and intelligent AI.',
    difficulty: 'Easy',
    controls: ['arrows', 'mouse', 'touch_drag'],
    instructions: 'Defend your goal line and angle your returns past the cyber goalkeeper.',
    themeColor: '#00F2FE',
    accentColor: '#10B981',
    badge: 'Retro',
    factory: (session, canvas, input, audio) => new PongGame(session, canvas, input, audio)
  },
  {
    id: 'invaders',
    title: 'Alien Vanguard',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Marching enemy formations descend from orbit. Use defensive bunkers and timing to eliminate the swarm.',
    difficulty: 'Hard',
    controls: ['arrows', 'space', 'touch_action'],
    instructions: 'Slide along the ground and fire up at the advancing ranks before they reach Earth.',
    themeColor: '#10B981',
    accentColor: '#EF4444',
    badge: 'Retro'
  },
  {
    id: 'bubble-shooter',
    title: 'Bubble Nova',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Aim and fire colored orbs to match 3 or more, causing cascading chain-reaction bubble explosions.',
    difficulty: 'Easy',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Aim the pointer and tap to launch bubbles into matching clusters.',
    themeColor: '#FF007F',
    accentColor: '#00F2FE',
    badge: 'Casual'
  },
  {
    id: 'fruit-catcher',
    title: 'Fruit Frenzy Drop',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Catch delicious falling fruits in your basket while dodging hazardous explosive bombs.',
    difficulty: 'Easy',
    controls: ['arrows', 'touch_drag'],
    instructions: 'Move your basket to catch strawberries and watermelons, avoid ticking bombs.',
    themeColor: '#FFD700',
    accentColor: '#EF4444',
    badge: 'Casual'
  },
  {
    id: 'retro-tank',
    title: 'Iron Tank 1985',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Command a heavy armored tank, blow open brick ramparts, and eliminate rival tanks in urban arenas.',
    difficulty: 'Hard',
    controls: ['wasd', 'mouse', 'touch_dpad'],
    instructions: 'Drive with D-Pad or WASD and fire explosive shells to eliminate enemy armor.',
    themeColor: '#10B981',
    accentColor: '#FFD700',
    badge: 'Action'
  },
  {
    id: 'lunar-lander',
    title: 'Lunar Gravity Lander',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Delicate thruster control on harsh extraterrestrial terrain with limited fuel and zero-gravity drift.',
    difficulty: 'Hard',
    controls: ['arrows', 'touch_action'],
    instructions: 'Carefully feather thrusters to land gently on the designated launchpad.',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Retro'
  },
  {
    id: 'centipede-blast',
    title: 'Neon Centipede',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Fast-paced shooter where winding bugs divide into smaller creatures upon impact.',
    difficulty: 'Hard',
    controls: ['arrows', 'space', 'touch_action'],
    instructions: 'Rapid fire into descending segmented crawlers through a mushroom forest.',
    themeColor: '#10B981',
    accentColor: '#FF007F',
    badge: 'Classic'
  },
  {
    id: 'frog-cross',
    title: 'Cyber Hopper Cross',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Hop across speeding multi-lane cyber highways and floating magnetic logs across treacherous rivers.',
    difficulty: 'Medium',
    controls: ['arrows', 'swipe', 'touch_dpad'],
    instructions: 'Time your leaps to cross road traffic and river hazards safely to the bank.',
    themeColor: '#00F2FE',
    accentColor: '#10B981',
    badge: 'Classic'
  },
  {
    id: 'galaxy-rush',
    title: 'Warp Speed Invaders',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Hyperspace arcade shooter featuring spiraling dive-bombing alien commanders.',
    difficulty: 'Hard',
    controls: ['arrows', 'space', 'touch_action'],
    instructions: 'Dodge looping swoop attacks and deploy dual laser cannons.',
    themeColor: '#7928CA',
    accentColor: '#FFD700',
    badge: 'Retro'
  },
  {
    id: 'pinball-matrix',
    title: 'Matrix Pinball',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Kinetic ball physics with glowing neon bumpers, ramp loops, multiball triggers, and tilt saves.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_tap'],
    instructions: 'Left and Right arrows activate flippers. Keep the silver ball alive!',
    themeColor: '#FF007F',
    accentColor: '#FFD700',
    badge: 'New'
  },
  {
    id: 'missile-shield',
    title: 'Missile Defense Net',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Intercept incoming ballistic warheads before they strike six defensive civilian dome cities.',
    difficulty: 'Hard',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Click or tap in sky to detonate timed flak explosions that disintegrate falling rockets.',
    themeColor: '#EF4444',
    accentColor: '#00F2FE',
    badge: 'Strategy'
  },
  {
    id: 'marble-popper',
    title: 'Marble Spiral',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Roll colored spheres into a winding track before the chain reaches the golden skull portal.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Match 3 colors to collapse the advancing marble train.',
    themeColor: '#7928CA',
    accentColor: '#10B981',
    badge: 'Casual'
  },
  {
    id: 'sub-hunter',
    title: 'Depth Charge Sub',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Deploy explosive depth charges from a patrol destroyer against lurking deep-sea submarines.',
    difficulty: 'Medium',
    controls: ['arrows', 'space', 'touch_action'],
    instructions: 'Time charges so they sink and detonate at the exact depth of passing subs.',
    themeColor: '#00F2FE',
    accentColor: '#1E2233',
    badge: 'Retro'
  },
  {
    id: 'breakout-deluxe',
    title: 'Prism Blast FX',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Next-gen brick destruction with explosive explosive bricks, multiball splits, and lasers.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Keep all active balls airborne and trigger chain reactions.',
    themeColor: '#FFD700',
    accentColor: '#FF007F',
    badge: 'Hot'
  },
  {
    id: 'jewel-quest',
    title: 'Neon Gem Drop',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Fast-paced arcade falling gem matcher. Align gleaming crystals to unleash screen-clearing lasers.',
    difficulty: 'Easy',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Cycle falling gem pillars and match 3 or more horizontally or diagonally.',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Popular'
  },
  {
    id: 'qix-cyber',
    title: 'Cyber Grid Claim',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Carve out territory across a neon field while dodging erratic sparks and cyber entities.',
    difficulty: 'Hard',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Draw lines to claim 75% of the total board area without getting intercepted.',
    themeColor: '#10B981',
    accentColor: '#00F2FE',
    badge: 'Classic'
  },
  {
    id: 'bomber-arena',
    title: 'Grid Bomber Arena',
    category: 'arcade',
    categoryName: 'Arcade Classics',
    description: 'Drop timed bombs, blow open pathways, pick up flame upgrades, and trap rival bombers.',
    difficulty: 'Medium',
    controls: ['wasd', 'space', 'touch_action'],
    instructions: 'Place bombs with spacebar, stay out of blast lines, and eliminate rival bots.',
    themeColor: '#EF4444',
    accentColor: '#FFD700',
    badge: 'Action'
  },

  // ==================== REFLEX & ENDLESS (23-42) ====================
  {
    id: 'flappy-dash',
    title: 'Neon Flappy Dash',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Tap to flap through treacherous electrified neon spires with ultra-tight physics precision.',
    difficulty: 'Hard',
    controls: ['space', 'touch_tap'],
    instructions: 'Tap or press Space to give your cyber bird upward momentum. Don’t graze any pipes!',
    themeColor: '#00F2FE',
    accentColor: '#EC4899',
    badge: 'Hot',
    factory: (session, canvas, input, audio) => new FlappyDashGame(session, canvas, input, audio)
  },
  {
    id: 'tower-stack',
    title: 'Precision Tower Stack',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Stack sliding 3D blocks with millisecond timing. Any overhang gets sliced away!',
    difficulty: 'Medium',
    controls: ['space', 'touch_tap'],
    instructions: 'Tap when the sliding block aligns with the tower below to stack it perfectly.',
    themeColor: '#FFD700',
    accentColor: '#7928CA',
    badge: 'Popular',
    factory: (session, canvas, input, audio) => new TowerStackGame(session, canvas, input, audio)
  },
  {
    id: 'color-switch',
    title: 'Color Switch Vortex',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Bounce your color-shifting sphere through matching multi-colored rotating rings and barriers.',
    difficulty: 'Hard',
    controls: ['space', 'touch_tap'],
    instructions: 'Tap to jump up. You can only pass through barrier segments that match your current color.',
    themeColor: '#FF007F',
    accentColor: '#00F2FE',
    badge: 'Addictive'
  },
  {
    id: 'downward-jump',
    title: 'Helix Downward Jump',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Bounce down an infinite spiral tower, twisting the cylinder to drop through empty gaps.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_drag'],
    instructions: 'Drag left/right to rotate the helix maze so the bouncing ball drops down layers.',
    themeColor: '#7928CA',
    accentColor: '#10B981',
    badge: 'Featured'
  },
  {
    id: 'knife-target',
    title: 'Cyber Knife Target',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Fling laser blades into a spinning target wheel without hitting existing embedded knives.',
    difficulty: 'Medium',
    controls: ['space', 'touch_tap'],
    instructions: 'Tap to throw a knife. Fill the spinning target without colliding with your own blades.',
    themeColor: '#00F2FE',
    accentColor: '#EF4444',
    badge: 'Skill'
  },
  {
    id: 'endless-runner',
    title: 'Neon Cyber Runner',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Sprint across floating futuristic rooftops, jumping over gaps and sliding beneath laser barriers.',
    difficulty: 'Medium',
    controls: ['arrows', 'swipe', 'touch_dpad'],
    instructions: 'Up to jump, Down to slide. Collect glowing data cubes and survive the speed rush.',
    themeColor: '#00F2FE',
    accentColor: '#FFD700',
    badge: 'Hot'
  },
  {
    id: 'reaction-test',
    title: 'Neuro Reaction Test',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Test your brain’s raw reaction speed in milliseconds when the screen flashes cyber green.',
    difficulty: 'Easy',
    controls: ['space', 'touch_tap'],
    instructions: 'Wait for the screen to turn vibrant green, then tap immediately to record your reaction time.',
    themeColor: '#10B981',
    accentColor: '#00F2FE',
    badge: 'Benchmark'
  },
  {
    id: 'dodge-storm',
    title: 'Laser Dodge Storm',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Survive in an arena flooded with tracking lasers, bouncing energy pulses, and plasma storms.',
    difficulty: 'Hard',
    controls: ['arrows', 'mouse', 'touch_drag'],
    instructions: 'Move your light node continuously to evade an ever-thickening web of deadly projectiles.',
    themeColor: '#EF4444',
    accentColor: '#00F2FE',
    badge: 'Hardcore'
  },
  {
    id: 'neon-hop',
    title: 'Beat Hop 3D',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Hop from neon tile to neon tile in sync with pulsing synth rhythms without falling into the void.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_drag'],
    instructions: 'Drag your glowing ball so it lands squarely on the center of each upcoming platform.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Rhythm'
  },
  {
    id: 'gravity-flip',
    title: 'Gravity Flip Runner',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Defy gravity with a single tap to run on ceiling and floor, navigating deadly jagged spikes.',
    difficulty: 'Hard',
    controls: ['space', 'touch_tap'],
    instructions: 'Tap to instantly reverse gravity between floor and ceiling to dodge deadly spikes.',
    themeColor: '#00F2FE',
    accentColor: '#FF007F',
    badge: 'Action'
  },
  {
    id: 'timber-cyber',
    title: 'Cyber Tree Chopper',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Chop high-tech tree sections at lightning speed while jumping between left and right branches.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_tap'],
    instructions: 'Tap left or right side of screen to chop. Don’t let descending heavy branches hit your head!',
    themeColor: '#10B981',
    accentColor: '#FFD700',
    badge: 'Quick'
  },
  {
    id: 'tap-dash',
    title: 'ZigZag Dash',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Keep a speeding orb on an ultra-narrow 90-degree zig-zagging wall path with single taps.',
    difficulty: 'Hard',
    controls: ['space', 'touch_tap'],
    instructions: 'Tap to toggle 90-degree turns. Stay on the wall and scoop up diamond gems.',
    themeColor: '#FF007F',
    accentColor: '#00F2FE',
    badge: 'Addictive'
  },
  {
    id: 'jump-orbit',
    title: 'Orbit Ring Jumper',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Leap between rotating planetary orbits at the exact tangential moment of alignment.',
    difficulty: 'Medium',
    controls: ['space', 'touch_tap'],
    instructions: 'Tap to fling your probe from your current spinning orbit ring to the next.',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Cosmic'
  },
  {
    id: 'piano-rush',
    title: 'Magic Keys Rush',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Tap falling musical energy keys in 4 lanes without missing a single beat.',
    difficulty: 'Medium',
    controls: ['touch_tap', 'keyboard_dfjk'],
    instructions: 'Tap the four descending notes as they reach the bottom line.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Rhythm'
  },
  {
    id: 'missile-evade',
    title: 'Homing Jet Evader',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Fly an agile fighter jet and make chasing heat-seeking missiles collide with each other.',
    difficulty: 'Hard',
    controls: ['arrows', 'touch_drag'],
    instructions: 'Steer tightly in loops to fool pursuing guided missiles into crashing together.',
    themeColor: '#FFD700',
    accentColor: '#EF4444',
    badge: 'Skill'
  },
  {
    id: 'jumpy-cat',
    title: 'Cyber Jumper Bounce',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Ascend endless vertical platforms with spring pads, jetpacks, and moving ledges.',
    difficulty: 'Easy',
    controls: ['arrows', 'tilt', 'touch_drag'],
    instructions: 'Guide your bouncing character onto platforms to climb as high as possible.',
    themeColor: '#10B981',
    accentColor: '#00F2FE',
    badge: 'Endless'
  },
  {
    id: 'fall-down',
    title: 'Abyss Fall Down',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Roll down through randomly generated platform floor gaps before the screen ceiling crushes you.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Steer through floor holes to plunge downward ahead of the rising screen border.',
    themeColor: '#EF4444',
    accentColor: '#00F2FE',
    badge: 'Classic'
  },
  {
    id: 'laser-vault',
    title: 'Laser Vault Gym',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Jump and duck over rotating laser tripwires that increase in rotational velocity.',
    difficulty: 'Hard',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Time your jumps precisely as the revolving laser beams sweep across the floor.',
    themeColor: '#FF007F',
    accentColor: '#7928CA',
    badge: 'Tough'
  },
  {
    id: 'speed-tunnel',
    title: '3D Hyper Tunnel',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Hurtling down a twisting neon wireframe wormhole, dodging incoming geometric barricades.',
    difficulty: 'Hard',
    controls: ['arrows', 'touch_drag'],
    instructions: 'Rotate around the inner circumference of the warp tube to dodge obstacles.',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Hypnotic'
  },
  {
    id: 'shield-deflect',
    title: 'Orbital Shield Guard',
    category: 'reflex',
    categoryName: 'Reflex & Action',
    description: 'Spin a protective circular shield around a central core to deflect incoming cosmic projectiles.',
    difficulty: 'Medium',
    controls: ['arrows', 'mouse', 'touch_drag'],
    instructions: 'Rotate the shield segment to absorb bullets matching its color.',
    themeColor: '#00F2FE',
    accentColor: '#FFD700',
    badge: 'Defense'
  },

  // ==================== PUZZLE & LOGIC (43-62) ====================
  {
    id: 'game-2048',
    title: 'Neon 2048',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Slide matching numeric cyber tiles across a 4x4 matrix to combine values and reach the legendary 2048!',
    difficulty: 'Medium',
    controls: ['arrows', 'wasd', 'swipe'],
    instructions: 'Swipe in any direction. Matching number tiles slide together and double their values.',
    themeColor: '#FFD700',
    accentColor: '#00F2FE',
    badge: 'Popular',
    factory: (session, canvas, input, audio) => new Game2048(session, canvas, input, audio)
  },
  {
    id: 'ultimate-ttt',
    title: 'Cyber Tic-Tac-Toe AI',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Challenge a neural heuristic AI with selectable difficulty settings in a glowing neon grid.',
    difficulty: 'Easy',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Place 3 markers in a row, column, or diagonal while blocking the AI opponent.',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Classic',
    factory: (session, canvas, input, audio) => new TicTacToeGame(session, canvas, input, audio)
  },
  {
    id: 'memory-match',
    title: 'Holo Memory Cards',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Test your photographic memory by flipping pairs of cyberpunk icons in minimum moves and time.',
    difficulty: 'Easy',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Tap two cards to reveal them. Match all identical pairs to conquer the grid.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Brain',
    factory: (session, canvas, input, audio) => new MemoryCardsGame(session, canvas, input, audio)
  },
  {
    id: 'minesweeper',
    title: 'Cyber Sweeper 99',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Deduce hidden magnetic mines using numeric proximity hints on an encrypted grid field.',
    difficulty: 'Hard',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Click to reveal safe squares. Numbers reveal how many mines touch that cell.',
    themeColor: '#EF4444',
    accentColor: '#00F2FE',
    badge: 'Retro'
  },
  {
    id: 'block-drop',
    title: 'Matrix Block Drop',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Falling geometric tetrominoes that must be rotated and slotted into complete horizontal lines.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_dpad', 'space'],
    instructions: 'Rotate falling polyominoes, build full lines to clear rows and earn massive tetrises.',
    themeColor: '#00F2FE',
    accentColor: '#FFD700',
    badge: 'Legend'
  },
  {
    id: 'sudoku-mini',
    title: 'Sudoku Speed Grid',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Solve compact 6x6 and classic 9x9 Sudoku number puzzles with instant logical validation.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Fill the grid so every row, column, and subgrid contains unique digits 1-6.',
    themeColor: '#10B981',
    accentColor: '#7928CA',
    badge: 'Logic'
  },
  {
    id: 'sliding-puzzle',
    title: '15-Puzzle Slider',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Slide numbered hologram tiles using a single open slot to arrange them in sequential order.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Click adjacent tiles to slide them into the empty space until numbers are in 1-15 order.',
    themeColor: '#7928CA',
    accentColor: '#FFD700',
    badge: 'Classic'
  },
  {
    id: 'number-merge',
    title: 'Hexa Number Merge',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Drop hexagonal numbers onto a honeycomb grid. 3 matching numbers merge into the next rank.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Place hex chips on the board. Group at least three identical numbers to merge them.',
    themeColor: '#FF007F',
    accentColor: '#00F2FE',
    badge: 'Casual'
  },
  {
    id: 'pattern-recall',
    title: 'Simon Cyber Recall',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Memorize and replay ever-lengthening acoustic synth melodies and glowing light patterns.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Watch the sequence of illuminated pads, then repeat it without making a mistake.',
    themeColor: '#00F2FE',
    accentColor: '#FFD700',
    badge: 'Brain'
  },
  {
    id: 'match-3',
    title: 'Jewel Blitz Match-3',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Swap adjacent glowing gemstones to form lines of 3 or more, creating cascades of neon gems.',
    difficulty: 'Easy',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Swap adjacent gems to match 3 of the same color. Chain 4 or 5 for special blast bombs.',
    themeColor: '#FF007F',
    accentColor: '#7928CA',
    badge: 'Popular'
  },
  {
    id: 'pipe-connect',
    title: 'Cyber Pipe Flow',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Rotate conduit tiles to channel glowing plasma coolant from pump to reactor without leaks.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Click pipes to rotate them 90 degrees and complete the continuous energy circuit.',
    themeColor: '#00F2FE',
    accentColor: '#10B981',
    badge: 'Brain'
  },
  {
    id: 'sokoban-bot',
    title: 'Warehouse Bot Sokoban',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Push heavy isotope containers onto designated storage plates without getting boxes cornered.',
    difficulty: 'Hard',
    controls: ['arrows', 'wasd', 'touch_dpad'],
    instructions: 'Walk up to cargo crates to push them onto green goal pads. You cannot pull crates!',
    themeColor: '#FFD700',
    accentColor: '#7928CA',
    badge: 'Logic'
  },
  {
    id: 'lights-out',
    title: 'Cyber Lights Out',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Toggling one node flips its state and all 4 neighbors. Turn off every light on the grid.',
    difficulty: 'Hard',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Click cells to toggle them and their cardinal neighbors. Extinguish all illuminated nodes.',
    themeColor: '#00F2FE',
    accentColor: '#171A27',
    badge: 'Challenging'
  },
  {
    id: 'word-scramble',
    title: 'Crypto Word Hack',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Unscramble anagram letters under time pressure to crack encrypted security mainframe passwords.',
    difficulty: 'Easy',
    controls: ['keyboard', 'touch_tap'],
    instructions: 'Type or click letters in the correct order to spell the hidden tech keyword.',
    themeColor: '#10B981',
    accentColor: '#00F2FE',
    badge: 'Word'
  },
  {
    id: 'laser-reflector',
    title: 'Laser Prism Optics',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Position and angle angled mirrors to bounce a concentrated laser beam into target receptors.',
    difficulty: 'Hard',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Drag and rotate mirror prisms so the light beam reflects directly onto the sensor.',
    themeColor: '#FF007F',
    accentColor: '#00F2FE',
    badge: 'Physics'
  },
  {
    id: 'tangram-neon',
    title: 'Neon Tangram Shapes',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Assemble 7 geometric polygonal pieces into specified silhouette contours without overlaps.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Drag and rotate colorful polygons to fill the master outline.',
    themeColor: '#7928CA',
    accentColor: '#FFD700',
    badge: 'Creative'
  },
  {
    id: 'color-flood',
    title: 'Flood Fill Spectrum',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Flood the entire board into a single uniform color in fewer than 25 strategic moves.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Pick colors from the bottom bar to expand your starting corner flood.',
    themeColor: '#00F2FE',
    accentColor: '#FF007F',
    badge: 'Strategy'
  },
  {
    id: 'mastermind',
    title: 'Code Breaker Matrix',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Crack a secret 4-color code through deductive reasoning using exact and partial match clues.',
    difficulty: 'Hard',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Submit guesses and use black (exact) and white (color only) pegs to deduce the code.',
    themeColor: '#10B981',
    accentColor: '#FFD700',
    badge: 'Logic'
  },
  {
    id: 'tower-hanoi',
    title: 'Tower of Hanoi',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Transfer an entire stack of graduated rings to a third peg without placing a larger disk on a smaller one.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Move one disk at a time between 3 rods. Never put a larger disc on top of a smaller one.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Classic'
  },
  {
    id: 'word-search',
    title: 'Cyber Word Matrix',
    category: 'puzzle',
    categoryName: 'Puzzle & Logic',
    description: 'Find futuristic vocabulary hidden horizontally, vertically, and diagonally in a letter soup.',
    difficulty: 'Easy',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Drag across words in the letter grid to cross them off your checklist.',
    themeColor: '#00F2FE',
    accentColor: '#10B981',
    badge: 'Casual'
  },

  // ==================== SPORTS & PHYSICS (63-82) ====================
  {
    id: 'dunk-basketball',
    title: 'Cyber Dunk Shootout',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Pull back and fling neon basketballs with realistic parabolic arc trajectories into moving hoops.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Drag back to aim trajectory and release to swish the ball cleanly through the hoop.',
    themeColor: '#FFD700',
    accentColor: '#FF007F',
    badge: 'Hot',
    factory: (session, canvas, input, audio) => new DunkBasketballGame(session, canvas, input, audio)
  },
  {
    id: 'penalty-shootout',
    title: 'Neon Penalty Kick',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Flick soccer shots with curve and spin past an acrobatic robotic goalkeeper.',
    difficulty: 'Medium',
    controls: ['swipe', 'touch_drag'],
    instructions: 'Swipe quickly toward the net to kick the ball. Curve your swipe to impart ball spin.',
    themeColor: '#10B981',
    accentColor: '#00F2FE',
    badge: 'Sports'
  },
  {
    id: 'mini-golf',
    title: 'Retro Mini Golf 18',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Putt glowing golf balls over ramps, windmills, teleporters, and water hazards into the cup in par.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Drag away from the golf ball to adjust putt power and angle, then release.',
    themeColor: '#00F2FE',
    accentColor: '#10B981',
    badge: 'Popular'
  },
  {
    id: 'air-hockey',
    title: 'Glow Air Hockey 3D',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Fast-paced, frictionless table air hockey with bank shots, high-speed ricochets, and smart AI.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Control your mallet with touch or mouse to slam the puck into the opposing goal.',
    themeColor: '#00F2FE',
    accentColor: '#FF007F',
    badge: 'Competitive'
  },
  {
    id: 'table-tennis',
    title: 'Laser Table Tennis',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Quick reaction ping-pong rallies against CPU challengers with topspin and smash returns.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Position paddle to intercept incoming ping pong balls and slice angles.',
    themeColor: '#FFD700',
    accentColor: '#00F2FE',
    badge: 'Fast'
  },
  {
    id: 'bowling-mini',
    title: 'Galaxy Bowling Alley',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Roll heavy bowling balls down cosmic hardwood lanes, apply hook spin, and knock down all 10 pins.',
    difficulty: 'Easy',
    controls: ['swipe', 'touch_drag'],
    instructions: 'Position ball, swipe forward with hook to score spares and strikes.',
    themeColor: '#7928CA',
    accentColor: '#FFD700',
    badge: 'Casual'
  },
  {
    id: 'pool-pocket',
    title: '8-Ball Neon Pool',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Top-down billiards with true physical ball collisions, cue power gauging, and English spin.',
    difficulty: 'Hard',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Line up cue stick with the cue ball, drag back for power, and sink solids or stripes.',
    themeColor: '#10B981',
    accentColor: '#00F2FE',
    badge: 'Classic'
  },
  {
    id: 'target-toss',
    title: 'Carnival Ring Toss',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Toss glowing rings onto neon pegs of varying point multipliers with precise angle and speed.',
    difficulty: 'Easy',
    controls: ['swipe', 'touch_drag'],
    instructions: 'Flick rings onto bottles and pegs to rack up carnival prize tickets.',
    themeColor: '#FF007F',
    accentColor: '#FFD700',
    badge: 'Casual'
  },
  {
    id: 'baseball-hit',
    title: 'Homerun Derby Neon',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Step up to the plate and swing at fastballs, curveballs, and changeups to launch 500ft homers.',
    difficulty: 'Medium',
    controls: ['space', 'touch_tap'],
    instructions: 'Time your bat swing the instant the pitched ball crosses the strike zone plate.',
    themeColor: '#FFD700',
    accentColor: '#00F2FE',
    badge: 'Action'
  },
  {
    id: 'soccer-flick',
    title: 'Free Kick Master',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Bend free kicks over defensive walls and past diving keepers into the top corner postage stamp.',
    difficulty: 'Medium',
    controls: ['swipe', 'touch_drag'],
    instructions: 'Swipe a curved line around the defensive wall into the upper corner of the goal.',
    themeColor: '#00F2FE',
    accentColor: '#10B981',
    badge: 'Skill'
  },
  {
    id: 'archery-master',
    title: 'Cyber Archery Range',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Draw bowstrings, compensate for dynamic crosswind velocities, and pierce bullseyes.',
    difficulty: 'Hard',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Hold and drag to draw bow, align for wind speed indicator, and release to let fly.',
    themeColor: '#10B981',
    accentColor: '#EF4444',
    badge: 'Precision'
  },
  {
    id: 'darts-neon',
    title: 'Neon 501 Darts',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Aim and fling darts at standard 501 dartboards with double and triple ring score multipliers.',
    difficulty: 'Medium',
    controls: ['swipe', 'touch_drag'],
    instructions: 'Swipe steadily toward the triple 20 or bullseye with consistent release speed.',
    themeColor: '#EF4444',
    accentColor: '#FFD700',
    badge: 'Pub'
  },
  {
    id: 'boxing-knockout',
    title: 'Cyber Boxing Ring',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Dodge, weave, throw jabs, hooks, and devastating uppercuts to KO cyber boxing opponents.',
    difficulty: 'Hard',
    controls: ['arrows', 'wasd', 'touch_dpad'],
    instructions: 'Dodge opponent swings and counter with quick jabs and heavy body punches.',
    themeColor: '#FF007F',
    accentColor: '#00F2FE',
    badge: 'Combat'
  },
  {
    id: 'curling-ice',
    title: 'Cyber Ice Curling',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Slide heavy granite stones down sheet ice and sweep friction paths into the button target.',
    difficulty: 'Medium',
    controls: ['swipe', 'touch_drag'],
    instructions: 'Launch the stone with calculated weight, then brush vigorously to extend curl.',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Winter'
  },
  {
    id: 'slingshot-birds',
    title: 'Plasma Slingshot',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Launch bouncy plasma projectiles to topple precarious fortresses and defeat alien critters.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Pull back slingshot, align trajectory against structural weak points, and let loose.',
    themeColor: '#EF4444',
    accentColor: '#FFD700',
    badge: 'Physics'
  },
  {
    id: 'badminton-rally',
    title: 'Hyper Badminton',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Smash aerodynamic shuttlecocks across the net with drop shots and jumping baseline spikes.',
    difficulty: 'Medium',
    controls: ['arrows', 'space', 'touch_action'],
    instructions: 'Position under the shuttlecock and hit Space to smash it past your rival.',
    themeColor: '#10B981',
    accentColor: '#00F2FE',
    badge: 'Sports'
  },
  {
    id: 'disc-golf',
    title: 'Neon Disc Golf',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Throw aerodynamic frisbee discs around trees and hazards into elevated chain baskets.',
    difficulty: 'Medium',
    controls: ['swipe', 'touch_drag'],
    instructions: 'Flick your disc with proper launch angle and hyzer tilt toward the chain basket.',
    themeColor: '#FFD700',
    accentColor: '#10B981',
    badge: 'Outdoor'
  },
  {
    id: 'ragdoll-toss',
    title: 'Cyber Ragdoll Launch',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Catapult an elastic cybernetic ragdoll as far as possible through bounce pads and rocket boosters.',
    difficulty: 'Easy',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Launch with max angle, then trigger mid-air booster bursts to extend flight distance.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Fun'
  },
  {
    id: 'skate-halfpipe',
    title: 'Halfpipe Vert Pro',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Pump for vertical speed in a neon halfpipe and pull off 900 spins, kickflips, and tail grabs.',
    difficulty: 'Hard',
    controls: ['arrows', 'space', 'touch_dpad'],
    instructions: 'Press Down on descents to pump speed, Up on lips to launch into aerial trick combos.',
    themeColor: '#00F2FE',
    accentColor: '#FF007F',
    badge: 'Extreme'
  },
  {
    id: 'water-ski',
    title: 'Hydro Slalom Jet',
    category: 'sports',
    categoryName: 'Sports & Physics',
    description: 'Carve water waves behind a speed boat, cutting through slalom buoys without wiping out.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_drag'],
    instructions: 'Lean left and right to weave around gate buoys while holding boat tension.',
    themeColor: '#00F2FE',
    accentColor: '#10B981',
    badge: 'Water'
  },

  // ==================== RACING & PLATFORMERS (83-102) ====================
  {
    id: 'highway-dodge',
    title: 'Cyber Highway Racer',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Weave at 200 MPH through dense multi-lane highway traffic in a tuned neon supercar.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Steer between traffic lanes, draft behind trucks for turbos, and avoid pileups.',
    themeColor: '#FF007F',
    accentColor: '#00F2FE',
    badge: 'Hot',
    factory: (session, canvas, input, audio) => new HighwayRacerGame(session, canvas, input, audio)
  },
  {
    id: 'pixel-platformer',
    title: 'Vector Pixel Knight',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Run, jump, and wall-slide through perilous platform levels filled with buzzsaws and lava.',
    difficulty: 'Hard',
    controls: ['arrows', 'wasd', 'space', 'touch_dpad'],
    instructions: 'Use Arrow keys to run and jump. Wall-jump off vertical shafts to reach high portals.',
    themeColor: '#00F2FE',
    accentColor: '#FFD700',
    badge: 'Featured'
  },
  {
    id: 'endless-ski',
    title: 'Alpine Neon Ski',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Carve down steep snowy slopes, dodging evergreen pines, giant boulders, and legendary yetis.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_drag'],
    instructions: 'Weave left and right down the mountain to clear slalom flags and dodge obstacles.',
    themeColor: '#00F2FE',
    accentColor: '#FFFFFF',
    badge: 'Fast'
  },
  {
    id: 'drift-racer',
    title: 'Tokyo Drift 2D',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Throw your sports car into smoky four-wheel drifts around hairpin turns for massive drift points.',
    difficulty: 'Hard',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Turn sharply into corners and tap handbrake to enter power slides. Counter-steer to maintain.',
    themeColor: '#FFD700',
    accentColor: '#FF007F',
    badge: 'Popular'
  },
  {
    id: 'kart-sprint',
    title: 'Micro Kart Grand Prix',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Top-down arcade kart racing with speed boost pads, banana peels, and homing missiles.',
    difficulty: 'Medium',
    controls: ['arrows', 'wasd', 'touch_dpad'],
    instructions: 'Steer around circuit tracks, hit booster stripes, and cross the checkered finish line 1st.',
    themeColor: '#10B981',
    accentColor: '#00F2FE',
    badge: 'Fun'
  },
  {
    id: 'bridge-runner',
    title: 'Infinity Bridge Sprint',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Dash across a collapsing suspension bridge over a glowing volcanic chasm at breakneck speed.',
    difficulty: 'Hard',
    controls: ['arrows', 'swipe', 'touch_dpad'],
    instructions: 'Leap over broken floor planks and dodge falling rock pillars without slowing down.',
    themeColor: '#EF4444',
    accentColor: '#FFD700',
    badge: 'Intense'
  },
  {
    id: 'cave-escape',
    title: 'Cave Jetpack Escape',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Navigate a low-gravity rocket pod through jagged caverns with rising underground magma.',
    difficulty: 'Hard',
    controls: ['space', 'touch_tap'],
    instructions: 'Hold Space or tap to fire vertical thrusters and stay between ceiling stalactites and ground floor.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Hardcore'
  },
  {
    id: 'neon-bike',
    title: 'Tron Light Cycle',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Race light bikes leaving solid glowing energy trails. Trap your opponent into crashing into your wall.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Make sharp 90-degree turns. Never cross an existing laser wall trail!',
    themeColor: '#00F2FE',
    accentColor: '#FF007F',
    badge: 'Classic'
  },
  {
    id: 'traffic-escape',
    title: 'Gridlock Traffic Escape',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Slide cars out of dense parking lot traffic jams in the proper sequence to let the sports car exit.',
    difficulty: 'Easy',
    controls: ['mouse', 'touch_drag'],
    instructions: 'Slide vehicles forward and backward to clear an open path to the exit arrow.',
    themeColor: '#FFD700',
    accentColor: '#EF4444',
    badge: 'Puzzle'
  },
  {
    id: 'rooftop-dash',
    title: 'Cyber Rooftop Parkour',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Free-run across towering skyscrapers, vaulting over ventilation pipes and sliding under billboards.',
    difficulty: 'Medium',
    controls: ['arrows', 'space', 'touch_dpad'],
    instructions: 'Keep your momentum high with timed jumps, wall vaults, and roll landings.',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Action'
  },
  {
    id: 'hover-rally',
    title: 'Anti-Gravity Hover Cup',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Pilot magnetic hovercrafts at Mach 1 along banked zero-G magnetic ribbon tracks.',
    difficulty: 'Hard',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Keep craft centered on energy ribbons and grab speed-booster pickups.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Sci-Fi'
  },
  {
    id: 'turbo-boat',
    title: 'Offshore Powerboat GP',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Bounce twin-engine catamarans across ocean swells, navigating buoy channels and ramp jumps.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Steer around ocean buoys and launch off wave crests for airborne shortcuts.',
    themeColor: '#00F2FE',
    accentColor: '#10B981',
    badge: 'Water'
  },
  {
    id: 'motocross-trials',
    title: 'Neon Dirt Trials',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Balance a dirt motorbike across scrap metal ramps, giant tires, and hazardous suspension loops.',
    difficulty: 'Hard',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Accelerate with Up, Brake with Down, Lean with Left and Right to nail smooth landings.',
    themeColor: '#FFD700',
    accentColor: '#EF4444',
    badge: 'Skill'
  },
  {
    id: 'submarine-trench',
    title: 'Deep Trench Sub Sprint',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Pilot an explorer submersible through deep volcanic hydrothermal vents avoiding sea mines.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_drag'],
    instructions: 'Steer deep submarine between thermal vents and salvage sunken cargo crates.',
    themeColor: '#00F2FE',
    accentColor: '#7928CA',
    badge: 'Deep'
  },
  {
    id: 'train-switch',
    title: 'Metro Rail Switcher',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Switch track junctions in real time to guide speeding express bullet trains to matching color stations.',
    difficulty: 'Medium',
    controls: ['mouse', 'touch_tap'],
    instructions: 'Click switch tracks to divert trains and prevent head-on train collisions.',
    themeColor: '#10B981',
    accentColor: '#FFD700',
    badge: 'Strategy'
  },
  {
    id: 'space-corridor',
    title: 'Starship Trench Run',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Fly down a planetary dreadnought defense trench, dodging automated laser turrets and blast doors.',
    difficulty: 'Hard',
    controls: ['arrows', 'space', 'touch_dpad'],
    instructions: 'Dodge descending blast shutters and launch torpedoes into exhaust ports.',
    themeColor: '#00F2FE',
    accentColor: '#FF007F',
    badge: 'Epic'
  },
  {
    id: 'neon-skater',
    title: 'Cyber Inline Skater',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Skate along neon sidewalks, grinding glowing guardrails and collecting battery tokens.',
    difficulty: 'Medium',
    controls: ['arrows', 'space', 'touch_dpad'],
    instructions: 'Jump onto rails to grind for bonus multipliers and duck under overhead cables.',
    themeColor: '#FF007F',
    accentColor: '#00F2FE',
    badge: 'Cool'
  },
  {
    id: 'tank-rush',
    title: 'Blitz Tank Charge',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Drive an armored tank through battlefield barricades, blowing up roadblocks and enemy pillboxes.',
    difficulty: 'Medium',
    controls: ['arrows', 'space', 'touch_action'],
    instructions: 'Advance continuously, blasting defensive anti-tank guns and dodging landmines.',
    themeColor: '#10B981',
    accentColor: '#EF4444',
    badge: 'Action'
  },
  {
    id: 'desert-buggy',
    title: 'Dune Buggy Storm',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Blast a sand buggy across dynamic rolling dunes, catching massive air off ridge lines.',
    difficulty: 'Medium',
    controls: ['arrows', 'touch_dpad'],
    instructions: 'Control pitch in mid-air to land parallel with downslopes for speed boosts.',
    themeColor: '#FFD700',
    accentColor: '#7928CA',
    badge: 'Offroad'
  },
  {
    id: 'hyper-drop',
    title: 'Gravity Well Plunge',
    category: 'racing',
    categoryName: 'Racing & Speed',
    description: 'Plunge headfirst into a black hole accretion disc, swerving past orbiting spatial debris.',
    difficulty: 'Hard',
    controls: ['arrows', 'mouse', 'touch_drag'],
    instructions: 'Navigate your capsule through gravitational distortion rings without striking asteroid chunks.',
    themeColor: '#7928CA',
    accentColor: '#00F2FE',
    badge: 'Cosmic'
  }
];

export class GameRegistry {
  constructor() {
    this.games = GAMES_DATA;
    this.categories = CATEGORIES;
  }

  getAllGames() {
    return this.games;
  }

  getGameById(id) {
    return this.games.find(g => g.id === id) || null;
  }

  getFeaturedGame() {
    return this.getGameById('snake') || this.games[0];
  }

  getGamesByCategory(catId) {
    if (!catId || catId === 'all') return this.games;
    return this.games.filter(g => g.category === catId);
  }

  searchGames(query) {
    if (!query) return this.games;
    const q = query.toLowerCase().trim();
    return this.games.filter(g => 
      g.title.toLowerCase().includes(q) ||
      g.categoryName.toLowerCase().includes(q) ||
      g.description.toLowerCase().includes(q)
    );
  }

  getCategoryCount(catId) {
    if (catId === 'all') return this.games.length;
    return this.games.filter(g => g.category === catId).length;
  }
}

export const gameRegistry = new GameRegistry();
